### ISSUE TITLE
uninitialized is deprecated

### ISSUE THREAD

**Issue by Mark-Simulacrum** [NuxiNL/cloudabi#18]
https://github.com/NuxiNL/cloudabi/blob/106ec68322ad99a725ac85ef139884b0f99d8d5b/generator/rust.py#L284

This line should likely be changed to use mem::zeroed() if I'm following correctly that these are C-like structs that are being initialized.

It is not currently defined to perform the reference and field access on the uninitialized memory too, whereas with zeroed this should be fine (at least as I understand it, though I cannot be 100% certain, as some of these details are still in flux).

**Comment by m-ou-se** [comment]
`mem::zeroed()` doesn't seem ideal either, as some structs contain `enum`s that don't have a 0 variant.

I'll try to change the generator to actually generate valid values in these tests.

**Comment by m-ou-se** [comment]
Fixed! Published as `cloudabi` crate 0.1.0.

**Comment by Mark-Simulacrum** [comment]
Thanks for the quick fix! I missed that there were some enums among them.
