### ISSUE TITLE
Publish rust crate sources

### ISSUE THREAD

**Issue by mcandre** [NuxiNL/cloudabi#8]
@m-ou-se Thank you for publishing crates to integrate Rust with CloudABI! Could the source for the argdata and cloudabi crates be posted as well? Not sure if these are generated directly from the C or what.

By the way, would love to see the argdata crate build in Rust stable. Is there a way to get this to work without depending on the nightly `try_from` feature?

**Comment by m-ou-se** [comment]
The `cloudabi` crate is generated from [`cloudabi.txt`](https://github.com/NuxiNL/cloudabi/blob/master/cloudabi.txt), and the generated sources are available in this repository as well: In the [`rust/` directory](https://github.com/NuxiNL/cloudabi/blob/master/rust/cloudabi.rs)

The source of the `argdata` crate is published here in the [`nuxinl/argdata-rust` repository](https://github.com/nuxinl/argdata-rust).

**Comment by m-ou-se** [comment]
I opened https://github.com/NuxiNL/argdata-rust/issues/1 to make it work on Rust stable. I will make some time this week to work on that.
